### ISSUE TITLE
 HDMI 接口楼主能用吗，有没有办法外接显示器呢

### ISSUE THREAD

**Issue by xinjiajuan** [qinglt/NH50_70RA-Z7M-CT5NA-Hackintosh#1]
问题如标题

**Comment by qinglt** [comment]
hdmi用不了，有的机型似乎可以用minidp接口外接，或者你可以尝试用usb转接

**Comment by xinjiajuan** [comment]
> hdmi用不了，有的机型似乎可以用minidp接口外接，或者你可以尝试用usb转接
https://github.com/kirainmoe/tongfang-macos/issues/10
如同这个所说，外接拓展坞的方法可行吗，用 displaylink 的方案

**Comment by xinjiajuan** [comment]
我的机器就是 z7-ct5na
